# Generated by Django 3.1.6 on 2021-02-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lopsinhvien', '0002_student_lop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='tieusu',
            field=models.TextField(max_length=100),
        ),
    ]
